### ISSUE TITLE
Custom tensorflow model

### ISSUE THREAD

**Issue by vidalsasun** [OvidijusParsiunas/myvision#14]
Can i load a custom trained model to autodetect labels as COCO-SSD?

Thank you

**Comment by OvidijusParsiunas** [comment]
Hey @vidalsasun, thankyou very much for the question!
You can certainly use your own custom models as long as they are compatible with [TensorFlow.js](https://www.tensorflow.org/js/). At the current moment, in order to do this you will have to fork the project and edit the `startMachineLearning` function to read your custom model instead of the currently used Coco-SSD model.
The use of custom models is certainly a very interesting use case and I will consider implementing it into the app in the future!
