### ISSUE TITLE
Loss of detail with very small bounding boxes

### ISSUE THREAD

**Issue by m345054** [OvidijusParsiunas/myvision#42]
Reproduce:
1. Load a 512x512 image and accurately label a very small object with full zoom.
2. Export (VOC XML or Yolo Text)
3. Open a new tab and reimport

**Comment by OvidijusParsiunas** [comment]
Hey @m345054, thankyou very much for raising the issue. Just so I understand the problem more clearly, could you elaborate on what the loss is? Is the data that is recorded in the exported file incorrect or is it the drawn bounding boxes on the reimport that are causing the problems? Also, may I ask what the magnitude of the loss is?

If you could perhaps provide data examples/screenshots, it would be very helpful to diagnose the problem!
Thankyou!

**Comment by m345054** [comment]
Hello I attached some screenshots. I can later debug if the error appears while exporting or when its reimported.
I labeled the cross exactly at the pixels border but when reimporting a small gap appears. 
<img width="1579" alt="example1" src="https://user-images.githubusercontent.com/26409801/206661497-b6fb64e0-1835-4339-98ee-be27c2f04993.png">
<img width="575" alt="example1zoomed" src="https://user-images.githubusercontent.com/26409801/206661541-62250c5c-18b9-4a99-9274-ae5b126dfab8.png">

Reimport:
<img width="1042" alt="reimportzoomed" src="https://user-images.githubusercontent.com/26409801/206661568-109175fc-4135-4783-9c77-039a30d7688c.png">
<img width="555" alt="reimportzoomed2" src="https://user-images.githubusercontent.com/26409801/206661946-03328d68-7b91-4eea-b5cd-3492549f1d3f.png">

**Comment by OvidijusParsiunas** [comment]
Thankyou for the explanation! I believe I have fixed the problem on a local version of the app, but I need to do a lot of thorough testing to make sure that I haven't broken any functionality which is currently correct.

Just to give a bit of clarity on why you were observing the issue:
Zoom functionality has been problematic in the past because the app doesn't actually zoom in the picture but instead expands it and crops the overflowing parts. When the user draws a bounding box/polygon on the zoomed in picture, the app has information of the shape's coordinates (pixels) on the screen (canvas element) and not the pixels relative to the original not zoomed in image. Hence, the app needs to perform calculations in order to identify how each zoomed in shape coordinate maps to the not zoomed in image coordinate. This is where data loss happens as this calculation is relatively cumbersome which involves rounding, hence resulting in data loss.

To note, if you zoom in and draw a bounding box with coordinates that would be in-between pixels of the original image, the app can only assume and guess (by rounding) which pixel is the coordinate meant to be on. Hence when you export data and import it on another browser tab - the two apps may draw shapes slightly differently as the original still has shapes between pixels.

Furthermore, this is explicitly problematic in VOC.XML as it only accepts integer coordinates, whereas when you zoom in - you are drawing very fine decimal place coordinates, thus when the app rounds up the coordinates to integers they may not be exactly what you have drawn. Unfortunately this is a limitation of this format which is impossible to get around, however the app will try to be as precise as possible.

**Comment by OvidijusParsiunas** [comment]
Bounding box result data should be much more accurate now.

**Comment by m345054** [comment]
Awesome thank you for your help
