### ISSUE TITLE
myvision can not deploy to server like flask.

### ISSUE THREAD

**Issue by 584251395** [OvidijusParsiunas/myvision#47]
appBundle.2404691effe4ecfa2988.js:2 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')

**Comment by OvidijusParsiunas** [comment]
Hi @584251395, can you provide me with some context around what you are trying to achieve and what tools you are using, thanks!

**Comment by 584251395** [comment]
i'm try to build a python web project with flask, and import the javascript file appBunde , it shows above errors  in the web browser, I have used published file of myvision.which still not work.

**Comment by OvidijusParsiunas** [comment]
Based on your comments I am assuming that you are attempting to do server side rendering via flask. A common problem with server side rendering is the fact that the `window` object is not recognised by the server (flask) and can only be understood by the client's browser, hence because MyVision has been initially designed to be a website rendered by the browser, the `window` object must be accessible.

Therefore, I am not quite sure if it is possible to achieve your objective with server side rendering and would instead recommend using a CDN approach. Finally to sum it up, the issue that you are facing does not look like it stems from the MyVision code itself but instead from the platform that you are using. Furthermore, the app is currently tailored to run as a standalone website on the browser and whilst I am more than happy for it to be reused on other platforms, the amount of assistance I can provide on them is limited.

I am going to close this issue as it is beyond the scope of MyVision, however if there are any details that anyone can add to assist with this problem, you are more than welcome to add them in the comments below. Thankyou!
